version: '2'
services:
  transmission:
    image: haugene/transmission-openvpn:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "9091:9091"
    volumes:
      - "/Volumes/One Touch/Music/drivers/video/:/data"
      - "/Users/chenda/Documents/Mullvad:/etc/openvpn/custom/"
    environment:
      - OPENVPN_PROVIDER=MULLVAD
      - OPENVPN_CONFIG=us_sea
      - OPENVPN_USERNAME=7126559067259501
      - OPENVPN_PASSWORD=pass
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.86.0/24
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0

#  image: haugene/transmission-openvpn-proxy
#  links:
#    - transmission
#  ports:
#    - 8080:8080
#  volumes:
#    - /etc/localtime:/etc/localtime:ro

# rss:
#  image: haugene/transmission-rss
#  links:
#    - transmission
#  environment:
#    - RSS_URL=http://.../xxxxx.rss
